### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by xnxq1** [ymmmmmmmm/BeraChainTools#11]
![Снимок экрана 2024-01-27 073619](https://github.com/ymmmmmmmm/BeraChainTools/assets/122284418/eae541f1-8bbc-4ba2-ac47-37b53f7801c7)
Hello, can you tell me what this error is? I use a proxy like http://user:password@ip:port

**Comment by ymmmmmmmm** [comment]
Your porxy account password is incorrect and authentication failed.
