### ISSUE TITLE
Capcha problem

### ISSUE THREAD

**Issue by genso413** [ymmmmmmmm/BeraChainTools#12]
Hey! jus tried, entered my 2capcha key and gen this 2024-01-29 15:17:48.549 | WARNING  | main:get_2captcha_google_token:25 - {'errorId': 22, 'errorCode': 'ERROR_TASK_ABSENT', 'errorDescription': 'Task property is empty or not set. Please refer to API v2 documentation'}

**Comment by ymmmmmmmm** [comment]
This is a bug, it has been fixed, thank you for reminding me
