### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by neo-godlike** [ymmmmmmmm/BeraChainTools#2]
PS E:\cypto\BeraChainTools> python .\drip_tokens.py
2024-01-21 09:11:44.319 | ERROR    | __main__:claim:53 - ('Connection aborted.', InvalidURL('URL can\'t contain control characters. \'<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u\' (found at least \' \')'))
2024-01-21 09:11:44.320 | ERROR    | __main__:claim:54 - ('Connection aborted.', InvalidURL('URL can\'t contain control characters. \'<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u\' (found at least \' \')'))
Traceback (most recent call last):

  File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 769, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
           │    │                 └ None
           │    └ <function HTTPConnectionPool._get_conn at 0x0000023A9014FEC0>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0>
  File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 295, in _get_conn
    return conn or self._new_conn()
           │       │    └ <function HTTPSConnectionPool._new_conn at 0x0000023A901587C0>
           │       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0>
           └ None
  File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1070, in _new_conn
    return self.ConnectionCls(
           │    └ <class 'urllib3.connection.HTTPSConnection'>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0>
  File "E:\Python\Python312\Lib\site-packages\urllib3\connection.py", line 535, in __init__
    super().__init__(
  File "E:\Python\Python312\Lib\site-packages\urllib3\connection.py", line 146, in __init__
    super().__init__(
  File "E:\Python\Python312\Lib\http\client.py", line 878, in __init__
    self._validate_host(self.host)
    │    │              │    └ <property object at 0x0000023A9013F420>
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x0000023A9198D070>
    │    └ <function HTTPConnection._validate_host at 0x0000023A8E47E840>
    └ <urllib3.connection.HTTPSConnection object at 0x0000023A9198D070>
  File "E:\Python\Python312\Lib\http\client.py", line 1280, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
          │                                                   └ '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoan...
          └ <class 'http.client.InvalidURL'>

http.client.InvalidURL: URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')

During handling of the above exception, another exception occurred:

哈哈哈 我冲了100块 一下给我run没了 也没领到 这个流程有点。。 我们一起维护吧

这是什么问题呢

**Comment by ymmmmmmmm** [comment]
> PS E:\cypto\BeraChainTools> python .\drip_tokens.py 2024-01-21 09:11:44.319 | ERROR | **main**:claim:53 - ('Connection aborted.', InvalidURL('URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')')) 2024-01-21 09:11:44.320 | ERROR | **main**:claim:54 - ('Connection aborted.', InvalidURL('URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')')) Traceback (most recent call last):
> 
> File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 769, in urlopen conn = self._get_conn(timeout=pool_timeout) │ │ └ None │ └ <function HTTPConnectionPool._get_conn at 0x0000023A9014FEC0> └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0> File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 295, in _get_conn return conn or self._new_conn() │ │ └ <function HTTPSConnectionPool._new_conn at 0x0000023A901587C0> │ └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0> └ None File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1070, in _new_conn return self.ConnectionCls( │ └ <class 'urllib3.connection.HTTPSConnection'> └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0> File "E:\Python\Python312\Lib\site-packages\urllib3\connection.py", line 535, in **init** super().**init**( File "E:\Python\Python312\Lib\site-packages\urllib3\connection.py", line 146, in **init** super().**init**( File "E:\Python\Python312\Lib\http\client.py", line 878, in **init** self._validate_host(self.host) │ │ │ └ <property object at 0x0000023A9013F420> │ │ └ <urllib3.connection.HTTPSConnection object at 0x0000023A9198D070> │ └ <function HTTPConnection._validate_host at 0x0000023A8E47E840> └ <urllib3.connection.HTTPSConnection object at 0x0000023A9198D070> File "E:\Python\Python312\Lib\http\client.py", line 1280, in _validate_host raise InvalidURL(f"URL can't contain control characters. {host!r} " │ └ '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoan... └ <class 'http.client.InvalidURL'>
> 
> http.client.InvalidURL: URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')
> 
> During handling of the above exception, another exception occurred:
> 
> 哈哈哈 我冲了100块 一下给我run没了 也没领到 这个流程有点。。 我们一起维护吧
> 
> 这是什么问题呢

铁子你代理url怎么填的

**Comment by neo-godlike** [comment]
> > PS E:\cypto\BeraChainTools> python .\drip_tokens.py 2024-01-21 09:11:44.319 | ERROR | **main**:claim:53 - ('Connection aborted.', InvalidURL('URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')')) 2024-01-21 09:11:44.320 | ERROR | **main**:claim:54 - ('Connection aborted.', InvalidURL('URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')')) Traceback (most recent call last):
> > File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 769, in urlopen conn = self._get_conn(timeout=pool_timeout) │ │ └ None │ └ <function HTTPConnectionPool._get_conn at 0x0000023A9014FEC0> └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0> File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 295, in _get_conn return conn or self._new_conn() │ │ └ <function HTTPSConnectionPool._new_conn at 0x0000023A901587C0> │ └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0> └ None File "E:\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1070, in _new_conn return self.ConnectionCls( │ └ <class 'urllib3.connection.HTTPSConnection'> └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000023A91916FC0> File "E:\Python\Python312\Lib\site-packages\urllib3\connection.py", line 535, in **init** super().**init**( File "E:\Python\Python312\Lib\site-packages\urllib3\connection.py", line 146, in **init** super().**init**( File "E:\Python\Python312\Lib\http\client.py", line 878, in **init** self._validate_host(self.host) │ │ │ └ <property object at 0x0000023A9013F420> │ │ └ <urllib3.connection.HTTPSConnection object at 0x0000023A9198D070> │ └ <function HTTPConnection._validate_host at 0x0000023A8E47E840> └ <urllib3.connection.HTTPSConnection object at 0x0000023A9198D070> File "E:\Python\Python312\Lib\http\client.py", line 1280, in _validate_host raise InvalidURL(f"URL can't contain control characters. {host!r} " │ └ '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoan... └ <class 'http.client.InvalidURL'>
> > http.client.InvalidURL: URL can't contain control characters. '<!doctype html><html data-adblockkey="mfwwdqyjkozihvcnaqebbqadswawsajbalqudfetxrn0hr05fup7ejt77xynpmrbpmy4vk8kyihnknpednjoanjcaxdxckqjn0nxkzjl7tcijd8aohxk158caweaaq==_vcpxxoo86hlgwmqe4itkit33u' (found at least ' ')
> > During handling of the above exception, another exception occurred:
> > 哈哈哈 我冲了100块 一下给我run没了 也没领到 这个流程有点。。 我们一起维护吧
> > 这是什么问题呢
> 
> 铁子你代理url怎么填的

铁子你用的是哪个代理 推荐一下 我的无法提取url

**Comment by ymmmmmmmm** [comment]
就是那种api提取，访问一下链接，就返回ip:port的。你谷歌搜搜基本上代理商都会有api提取接口。

**Comment by neo-godlike** [comment]
> 就是那种api提取，访问一下链接，就返回ip:port的。你谷歌搜搜基本上代理商都会有api提取接口。

ok 代理正常了 但是验证好像过不了目前报错
{'errorId': 1, 'errorCode': 'ERROR_NO_SUCH_CAPCHA_ID', 'errorDescription': '验证码任务已失效'}

**Comment by ymmmmmmmm** [comment]
多试几次看看，yescaptcha我测试是可以过的，如果还是不行的话明天我加个别的分数高的平台。

**Comment by badminer** [comment]
> 多试几次看看,yescaptcha我测试是可以过的,如果还是不行的话明天我加个别的分数高的平台.者去我另外一个项目仓库,有二维码。

Add 2captcha.com

**Comment by ymmmmmmmm** [comment]
> > 多试几次看看,yescaptcha我测试是可以过的,如果还是不行的话明天我加个别的分数高的平台.者去我另外一个项目仓库,有二维码。
> 
> Add 2captcha.com

听劝，已添加

**Comment by ymmmmmmmm** [comment]
Read the latest remdme.md and you will find the answer


`
from eth_account import Account
from loguru import logger

from bera_tools import BeraChainTools

account = Account.create()
logger.debug(f'address:{account.address}')
logger.debug(f'key:{account.key.hex()}')
client_key = 'You 2Captcha API Key'
bera = BeraChainTools(private_key=account.key, client_key=client_key, solver_provider='2captcha',
                      rpc_url='https://rpc.ankr.com/berachain_testnet')
# No Proxy
result = bera.claim_bera()
logger.debug(result.text)
# Use proxy
result = bera.claim_bera(proxies={'http': "http://127.0.0.1:8888", "https": "http://127.0.0.1:8888"})
logger.debug(result.text)
`

**Comment by ymmmmmmmm** [comment]
> I don't understand how to get this up and running. What file should I change and what .py file should I run?

Read the latest remdme.md and you will find the answer


`
from eth_account import Account
from loguru import logger

from bera_tools import BeraChainTools

account = Account.create()
logger.debug(f'address:{account.address}')
logger.debug(f'key:{account.key.hex()}')
client_key = 'You 2Captcha API Key'
bera = BeraChainTools(private_key=account.key, client_key=client_key, solver_provider='2captcha',
                      rpc_url='https://rpc.ankr.com/berachain_testnet')
# No Proxy
result = bera.claim_bera()
logger.debug(result.text)
# Use proxy
result = bera.claim_bera(proxies={'http': "http://127.0.0.1:8888", "https": "http://127.0.0.1:8888"})
logger.debug(result.text)
`

**Comment by badminer** [comment]
Where are the results saved?
