### ISSUE TITLE
Can't swap weth

### ISSUE THREAD

**Issue by KayNguyen97** [ymmmmmmmm/BeraChainTools#23]
![image](https://github.com/ymmmmmmmm/BeraChainTools/assets/126054099/4b80e32c-796d-4ee8-94a3-52f841f4bfb3)
pls help me, i can't swap usdc to weth , show error

**Comment by zrqgood** [comment]
这个问题怎么关闭了, 该问题还是存在, 按照提示说明也不可以
ValueError({'code': -32000, 'message': 'replacement transaction underpriced'})
