### ISSUE TITLE
大家是怎么解决ip 问题的

### ISSUE THREAD

**Issue by kaosZL** [ymmmmmmmm/BeraChainTools#27]
多账号领水得切换IP，大家是怎么解决的

**Comment by ymmmmmmmm** [comment]
仔细阅读readme，有使用代理。

**Comment by kaosZL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
