### ISSUE TITLE
hi why proxy uses?

### ISSUE THREAD

**Issue by lupupavlo** [ymmmmmmmm/BeraChainTools#3]
![image](https://github.com/ymmmmmmmm/BeraChainTools/assets/52676667/2892b3e1-e788-4e9b-861f-e124d8c41dcc)
no work

**Comment by lupupavlo** [comment]
PROXY_URL=http://user49:dDrS0DuK5wFAitMzy2Op@176.122.121.95:8001 i use this proxy

**Comment by ymmmmmmmm** [comment]
`utils.py` is not the main program, claim bera tokens please run `drip_tokens.py`
`PROXY_URL=http://example.com/get-proxy?nums=1 `
This configuration is the extraction link of the proxy. You cannot directly fill in the http proxy，If you want to modify the proxy directly, please use the `requests.post` section in `drip_tokens.py`

**Comment by lupupavlo** [comment]
do you have a link where to buy proxies that fit?

**Comment by lupupavlo** [comment]
i use this link https://api.asocks.com/api/v1/proxy-list/zzX8xNOJjGkDm9skCb9ha2SjiX5apn02.txt 
![image](https://github.com/ymmmmmmmm/BeraChainTools/assets/52676667/6dc5720d-5b19-4dcc-acb3-48526d9c291e)

**Comment by ymmmmmmmm** [comment]
Please set the extraction quantity to 1, that is, 1 IP will be returned for each visit.

**Comment by ymmmmmmmm** [comment]
Hi bro I have updated the proxy incoming method, read the redeme documentation
