### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by lupupavlo** [ymmmmmmmm/BeraChainTools#7]
why proxy you uses? link?

**Comment by ymmmmmmmm** [comment]
The berachain faucet limits IP requests, so use a proxy, link? You can modify the proxy extraction method and pass it in.

**Comment by tjuryakin** [comment]
> The berachain faucet limits IP requests, so use a proxy, link? You can modify the proxy extraction method and pass it in.

They changed something, the faucet does not work through the script, does it work for you? with my proxies (new and old) - the logs are returned Null

**Comment by lupupavlo** [comment]
I can use my addresses for this?
If I want my wallets, how can I write them because the format is wrong in the code and does not start.

**Comment by ymmmmmmmm** [comment]
`account = Account.from_key('xxxxxxxxxxxx')
bera = BeraChainTools(private_key=account.key, client_key=client_key,solver_provider='yescaptcha',rpc_url='https://rpc.ankr.com/berachain_testnet')`

If it cannot be started, please take a screenshot or tell me the error message

**Comment by lupupavlo** [comment]
you have telegram?

**Comment by ymmmmmmmm** [comment]
![WechatIMG184](https://github.com/ymmmmmmmm/BeraChainTools/assets/51306299/7deff9db-deb1-4b9d-ae47-5ad4ac66efbb)
