### ISSUE TITLE
500 error api

### ISSUE THREAD

**Issue by tjuryakin** [ymmmmmmmm/BeraChainTools#9]
They changed something, the faucet does not work through the script, does it work for you? with my proxies (new and old) - the logs are returned Null

I thought maybe you had an error and wrote my own faucet collector, but the same thing, the faucet api returns a 500 error.

I tried to take the finished product of another creator, but it was the same, and I checked the proxies 3 times, they work.

do you have a problem getting from the faucet now? or something is wrong on my side

I tried all captcha services, the problem is not with them, the proxy is also ok 🤷‍♂️

**Comment by xnxq1** [comment]
yes they changed the faucet. What about galxe? I tried to take points through selenium, but galxe sees that this is a simulator

**Comment by tjuryakin** [comment]
> yes they changed the faucet. What about galxe? I tried to take points through selenium, but galxe sees that this is a simulator

In theory, you can open a real browser with Selenium integration on a dedicated server and connect the captcha solution there, then it will work..

**Comment by ymmmmmmmm** [comment]
> They changed something, the faucet does not work through the script, does it work for you? with my proxies (new and old) - the logs are returned Null
> 
> I thought maybe you had an error and wrote my own faucet collector, but the same thing, the faucet api returns a 500 error.
> 
> I tried to take the finished product of another creator, but it was the same, and I checked the proxies 3 times, they work.
> 
> do you have a problem getting from the faucet now? or something is wrong on my side
> 
> I tried all captcha services, the problem is not with them, the proxy is also ok 🤷‍♂️

I re-ran the code and it can be collected normally. If there is an error, please upload the error information to facilitate troubleshooting.

**Comment by ymmmmmmmm** [comment]
> yes they changed the faucet. What about galxe? I tried to take points through selenium, but galxe sees that this is a simulator

In the near future, I will open source the galxe task code, including geetest
